version: "3.4"

services:

  mariadb:
    network_mode: traefik_default
    environment:
      MYSQL_INNODB_BUFFER_POOL_SIZE : ${MYSQL_INNODB_BUFFER_POOL_SIZE:-1G}
      MYSQL_INNODB_IO_CAPACITY : ${MYSQL_INNODB_IO_CAPACITY:-2400}
      MYSQL_INNODB_LOG_FILE_SIZE : ${MYSQL_INNODB_LOG_FILE_SIZE:-256M}
      MYSQL_INNODB_READ_IO_THREADS : ${MYSQL_INNODB_READ_IO_THREADS:-16}
      MYSQL_INNODB_WRITE_IO_THREADS : ${MYSQL_INNODB_WRITE_IO_THREADS:-16}
      MYSQL_OPTIMIZER_SEARCH_DEPTH : ${MYSQL_OPTIMIZER_SEARCH_DEPTH:-0}
      MYSQL_QUERY_CACHE_TYPE : ${MYSQL_QUERY_CACHE_TYPE:-0}
      MYSQL_QUERY_CACHE_SIZE : ${MYSQL_QUERY_CACHE_SIZE:-0}

  php:
    network_mode: traefik_default
    environment:
      ## Read instructions at https://wodby.com/docs/stacks/php/local/#xdebug
      PHP_XDEBUG: 1
      PHP_XDEBUG_MODE: debug
      PHP_IDE_CONFIG: serverName=${PROJECT_NAME}.localhost
      PHP_XDEBUG_IDEKEY: "${PROJECT_NAME}.localhost"
      PHP_XDEBUG_CLIENT_HOST: 172.17.0.1 # Linux
      PHP_XDEBUG_LOG: /tmp/php-xdebug.log
      PHP_XDEBUG_START_WITH_REQUEST: "yes"
      PHP_MAX_EXECUTION_TIME: ${PHP_MAX_EXECUTION_TIME:-120}
      PHP_POST_MAX_SIZE: ${PHP_POST_MAX_SIZE:-32M}
      PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT:-512M}
      PHP_UPLOAD_MAX_FILESIZE: ${PHP_UPLOAD_MAX_FILESIZE:-32M}
      #### SENDMAIL SUPPORT
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S ${PROJECT_NAME}_mailhog:1025
      #### BLACKFIRE SUPPORT
      #PHP_BLACKFIRE: 1
      #BLACKFIRE_CLIENT_ID: CLIENT_XXXXXX
      #BLACKFIRE_CLIENT_TOKEN: CLIENT_YYYYY
      #PHP_BLACKFIRE_AGENT_HOST: "${PROJECT_NAME}_blackfire"
      #### END BLACKFIRE SUPPORT

      # We need SSH_PRIVATE_KEY until
      # https://github.com/wodby/php/blob/master/7/docker-entrypoint.sh
      # applies the deprecation over init_ssh_client().
      SSH_PRIVATE_KEY: 1
    volumes:
      - ./.id:/etc/gotpl/id_rsa.tmpl
      - ./.ssh_config:/etc/gotpl/ssh_config.tmpl

  apache:
    network_mode: traefik_default
    environment:
      # For xdebug when we hold a breakpoint we need the server
      # wait until we release the request. APACHE_FCGI_PROXY_TIMEOUT
      # prevent the "Gateway Timeout"
      APACHE_FCGI_PROXY_TIMEOUT: 600
      # Our traefik needs the exact name instead just "php" since
      # it holds many containters and each one has it own unique name.
      APACHE_BACKEND_HOST: "${PROJECT_NAME}_php"
      APACHE_DOCUMENT_ROOT: /var/www/html/web/$PROJECT_BASE_PATH
    labels:
      # Minimal modifications to allow subdomain wildcard. Any URL that does not match with
      # taken domains like pma."project".localhost will fall intro apache container.
      traefik.frontend.rule: HostRegexp:${PROJECT_BASE_URL}, {subdomain:[a-z]+}.${PROJECT_BASE_URL}

  pma:
    network_mode: traefik_default
    environment:
      PMA_USER: root
      PMA_PASSWORD: $DB_ROOT_PASSWORD
      # Our traefik needs the exact name instead just "mariadb" since
      # it holds many containters and each one has it own unique name.
      PMA_HOST: "${PROJECT_NAME}_$DB_HOST"
    labels:
      - 'traefik.frontend.rule=Host:${PROJECT_NAME}.pma.localhost'

  mailhog:
    network_mode: traefik_default
    labels:
      - 'traefik.frontend.rule=Host:${PROJECT_NAME}.mailhog.localhost'

  node:
    container_name: ${PROJECT_NAME}_node
    network_mode: traefik_default
    user: "node"
#    image: "node:lts-jessie"
    volumes:
      - ./:/var/www/html

#  blackfire:
#    network_mode: traefik_default

#  chrome:
#    network_mode: traefik_default


# Just for legacy
#  frontend:
#    container_name: ${PROJECT_NAME}_frontend
#    image: frontid/docker-front-tools:latest
#    network_mode: traefik_default
#    volumes:
#      - ./:/var/www/html
#    command: tail -f /dev/null

#  terminus:
#    container_name: ${PROJECT_NAME}_terminus
#    network_mode: traefik_default
#    image: quay.io/pantheon-public/build-tools-ci
#    environment:
#      TERMINUS_CACHE_DIR: "/terminus/cache"
#      SSH_AUTH_SOCK: /ssh-agent
#      MACHINE_TOKEN: $MACHINE_TOKEN
#      SITE: $SITE
#    volumes:
#      - ./storage/terminus:/terminus/cache
#      - ./:/app:cached
#      - ./:/var/www/html
#      - $SSH_AUTH_SOCK:/ssh-agent # Forward local machine SSH key to docker
#    command: tail -f /dev/null

#  postgres:
#    container_name: ${PROJECT_NAME}_postgres
#    image: wodby/postgres:${POSTGRESS_TAG}
#    network_mode: traefik_default
#    stop_grace_period: 30s
#    environment:
#      POSTGRES_PASSWORD: password
#      POSTGRES_DB: db
#      POSTGRES_USER: db
#    volumes:
#      - ./:/var/www/html

#  postgis:
#    container_name: ${PROJECT_NAME}_postgis
#    network_mode: traefik_default
#    image: mdillon/postgis
#    environment:
#      POSTGRES_PASSWORD: db
#      POSTGRES_USER: db
#      POSTGRES_DB: db
#      PGDATA: /var/lib/postgresql/data/pgdata
#    volumes:
#      - ./:/var/www/html

#  solr:
#    image: wodby/solr:$SOLR_TAG
#    container_name: "${PROJECT_NAME}_solr"
#    environment:
#      PROJECT_NAME: ${PROJECT_NAME}
#      SOLR_DEFAULT_CONFIG_SET: $SOLR_CONFIG_SET
#      SOLR_HEAP: ${SOLR_HEAP:-1024m}
#    network_mode: traefik_default
#    labels:
#      - 'traefik.frontend.rule=Host:${PROJECT_NAME}.solr.localhost'
#      - "traefik.http.routers.${PROJECT_NAME}_solr.rule=Host(`solr.${PROJECT_BASE_URL}`)"
#    volumes:
#      - ./:/var/www/html
#      - ${SOLR_CORE_CONFIG_DIR}:/opt/solr/server/solr/configsets/${PROJECT_NAME}
