#!/bin/bash

if [ $1 = "stop" ]; then
    echo "Stopping dockerizer traefik."
    cd ~/.local/share/traefik
    docker-compose stop
    cd - >> /dev/null
fi

if [ $1 = "start" ]; then
    echo "Starting dockerizer traefik."
    cd ~/.local/share/traefik
    docker-compose up -d
    cd - >> /dev/null
fi
