#!/bin/bash

if [ $1 = "stop" ]; then
    echo "Stopping dockerizer traefik."
    docker-compose -f ~/.local/share/traefik/docker-compose.yml stop
fi

if [ $1 = "start" ]; then
    echo "Starting dockerizer traefik."
    docker-compose -f ~/.local/share/traefik/docker-compose.yml start
fi
